<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

/**
 * ProductSeeder
 * Seeds the database with sample coffee products
 */
class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Hot Coffee (Velvet Flames)
            [
                'name' => 'Crimson Mocha',
                'description' => 'Dark cocoa espresso swirled with cherry essence',
                'ingredients' => 'Dark chocolate, cherry syrup, espresso, whipped cream',
                'flavor_notes' => 'Rich, deep, unforgettable',
                'origin_story' => 'A blend that whispers of midnight rendezvous and forbidden pleasures.',
                'category' => 'hot',
                'price' => 6.50,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'crimson mocha.jpg',
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Velvet Sin Latte',
                'description' => 'Caramel latte dusted with rose petals',
                'ingredients' => 'Caramel syrup, steamed milk, espresso, rose petals',
                'flavor_notes' => 'Smooth, creamy, floral',
                'origin_story' => 'Smooth temptation with a floral twist, like silk against your lips.',
                'category' => 'hot',
                'price' => 8.70,
                'special_price' => 7.50,
                'is_special' => true,
                'image_path' => 'velvet sin latte.jpg',
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Midnight Brew',
                'description' => 'Bold espresso with smoky aroma',
                'ingredients' => 'Dark roast espresso, smoked beans',
                'flavor_notes' => 'Bold, smoky, intense',
                'origin_story' => 'The perfect dose of dark comfort for souls who dance with shadows.',
                'category' => 'hot',
                'price' => 4.25,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'midnight brew.jpg',
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Whispered Desire',
                'description' => 'Vanilla-hazelnut cappuccino with cinnamon foam',
                'ingredients' => 'Vanilla syrup, hazelnut, cappuccino, cinnamon foam',
                'flavor_notes' => 'Sweet, nutty, warming',
                'origin_story' => 'Made to melt hearts with its gentle warmth and sweet whispers.',
                'category' => 'hot',
                'price' => 5.50,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'wispered desire.jpg',
                'display_order' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Amber Macchiato',
                'description' => 'Golden espresso layered with buttery toffee',
                'ingredients' => 'Espresso, toffee syrup, steamed milk, caramel drizzle',
                'flavor_notes' => 'Rich, buttery, elegant',
                'origin_story' => 'Elegance in a cup, golden as the morning sun through stained glass.',
                'category' => 'hot',
                'price' => 6.00,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'amber machiatto.jpg',
                'display_order' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Burnt Sugar Bliss',
                'description' => 'Espresso caramelized with raw sugar and sea salt',
                'ingredients' => 'Espresso, raw sugar, sea salt, caramel',
                'flavor_notes' => 'Intense, balanced, complex',
                'origin_story' => 'Intense yet balanced, like the perfect storm of sweetness and salt.',
                'category' => 'hot',
                'price' => 5.25,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'burnt sugar bliss.jpg',
                'display_order' => 6,
                'is_active' => true,
            ],

            // Cold Coffee (Frosted Allure)
            [
                'name' => 'Blush Cold Brew',
                'description' => 'Cold brew kissed with strawberry milk',
                'ingredients' => 'Cold brew coffee, strawberry milk, ice',
                'flavor_notes' => 'Light, sweet, addictive',
                'origin_story' => 'Light pink, lightly sweet, and entirely addictive like first love.',
                'category' => 'cold',
                'price' => 5.75,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'blush cold brew.png',
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Scarlet Frost',
                'description' => 'Iced espresso with red velvet cream foam',
                'ingredients' => 'Iced espresso, red velvet cream, ice',
                'flavor_notes' => 'Rich, creamy, dessert-like',
                'origin_story' => 'Looks like dessert, tastes like love in its purest form.',
                'category' => 'cold',
                'price' => 7.80,
                'special_price' => 6.75,
                'is_special' => true,
                'image_path' => 'scarlet frost.jpg',
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Honey Bloom Latte',
                'description' => 'Iced vanilla latte drizzled with honey',
                'ingredients' => 'Iced vanilla latte, honey, edible flowers',
                'flavor_notes' => 'Sweet, floral, refreshing',
                'origin_story' => 'Sweet as nectar, beautiful as a spring morning garden.',
                'category' => 'cold',
                'price' => 5.50,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'honey bloom latte.jpg',
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Moonlight Iced Latte',
                'description' => 'Espresso, oat milk, and lavender syrup',
                'ingredients' => 'Espresso, oat milk, lavender syrup, ice',
                'flavor_notes' => 'Calm, cool, romantic',
                'origin_story' => 'Calm, cool, and romantic like a moonlit garden walk.',
                'category' => 'cold',
                'price' => 5.25,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'moonlight iced latte.jpg',
                'display_order' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Berry Temptation',
                'description' => 'Mixed berry frappe with vanilla cream',
                'ingredients' => 'Mixed berries, frappe base, vanilla cream',
                'flavor_notes' => 'Sweet, tart, flirty',
                'origin_story' => 'Sweet, tart, and irresistibly flirty like a summer romance.',
                'category' => 'cold',
                'price' => 6.00,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'berry temptation.jpg',
                'display_order' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Sinful Caramel Chill',
                'description' => 'Cold coffee swirled with caramel and sea salt',
                'ingredients' => 'Cold coffee, caramel, sea salt, ice cream',
                'flavor_notes' => 'Indulgent, creamy, complex',
                'origin_story' => 'Indulgence at its best, like giving in to your deepest desires.',
                'category' => 'cold',
                'price' => 6.50,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'sinfull caramel chill.jpg',
                'display_order' => 6,
                'is_active' => true,
            ],

            // Non-Coffee (Nectar Teas and Tonics)
            [
                'name' => 'Crimson Bloom Tea',
                'description' => 'Hibiscus & rose infusion with honey lemon',
                'ingredients' => 'Hibiscus, rose petals, honey, lemon',
                'flavor_notes' => 'Light, floral, refreshing',
                'origin_story' => 'Light, floral, and refreshing like a gentle morning breeze.',
                'category' => 'non-coffee',
                'price' => 5.90,
                'special_price' => 4.50,
                'is_special' => true,
                'image_path' => 'crimson bloom tea.jpg',
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Golden Chai Lust',
                'description' => 'Saffron chai with almond milk',
                'ingredients' => 'Saffron, chai spices, almond milk',
                'flavor_notes' => 'Royal, aromatic, warming',
                'origin_story' => 'Royal and aromatic, made for slow sips and contemplation.',
                'category' => 'non-coffee',
                'price' => 5.25,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'golden chai lust.jpg',
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Sinful Matcha Kiss',
                'description' => 'Matcha latte with vanilla cream',
                'ingredients' => 'Matcha powder, vanilla cream, milk',
                'flavor_notes' => 'Sweet, earthy, serene',
                'origin_story' => 'Sweet serenity in green, like peace found in nature\'s embrace.',
                'category' => 'non-coffee',
                'price' => 5.75,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'sunful macha kiss.jpg',
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Lover\'s Lemonade',
                'description' => 'Sparkling lemonade with strawberry syrup',
                'ingredients' => 'Sparkling water, lemon, strawberry syrup, basil',
                'flavor_notes' => 'Tart, sweet, refreshing',
                'origin_story' => 'A fruity twist on classic refreshment, perfect for summer days.',
                'category' => 'non-coffee',
                'price' => 4.25,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'lemonade.jpg',
                'display_order' => 4,
                'is_active' => true,
            ],

            // Seasonal (Scarlet Limited)
            [
                'name' => 'Autumn Ember Latte',
                'description' => 'Pumpkin spice latte with cinnamon dust',
                'ingredients' => 'Pumpkin spice, cinnamon, nutmeg, latte',
                'flavor_notes' => 'Warm, cozy, spiced',
                'origin_story' => 'Warm and cozy like autumn evenings by the fireplace.',
                'category' => 'seasonal',
                'price' => 5.50,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'Autum Ember Latte.jpg',
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Winter Kiss Cocoa',
                'description' => 'Peppermint milk chocolate with whipped cream',
                'ingredients' => 'Peppermint, milk chocolate, whipped cream, candy cane',
                'flavor_notes' => 'Cool, sweet, festive',
                'origin_story' => 'A winter\'s kiss that warms the soul and delights the senses.',
                'category' => 'seasonal',
                'price' => 5.75,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'winter kiss cocoa.jpg',
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Summer Sin Spritz',
                'description' => 'Espresso lemonade - sparkling and tangy',
                'ingredients' => 'Espresso, lemonade, sparkling water',
                'flavor_notes' => 'Tangy, refreshing, energizing',
                'origin_story' => 'Sparkling, tangy, and devilishly refreshing for hot summer days.',
                'category' => 'seasonal',
                'price' => 5.00,
                'special_price' => null,
                'is_special' => false,
                'image_path' => 'summer sin spritz.jpg',
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Spring Blush Brew',
                'description' => 'Rose latte with raspberry cream',
                'ingredients' => 'Rose syrup, raspberry cream, latte',
                'flavor_notes' => 'Soft, delicate, floral',
                'origin_story' => 'Soft, delicate, and perfectly pink like spring\'s first bloom.',
                'category' => 'seasonal',
                'price' => 6.62,
                'special_price' => 5.25,
                'is_special' => true,
                'image_path' => 'spring blush brew.jpg',
                'display_order' => 4,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}

